# ---------------------- #
# site config            #
# ---------------------- #
name: Perry's tools
baseurl:
url: https://tool.yeh.sh
keywords: tools
description: Perry's tools

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
rouge: true
markdown: kramdown
timezone: America/Los_Angeles

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:

# ---------------------- #
# google analytics       #
# ---------------------- #
google_analytics: UA-11027907-1
