# ---------------------- #
# site config            #
# ---------------------- #
name: Perry's tools
baseurl:
url: http://tool.yeh.sh
keywords: tools
description: Perry's tools

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
pygments: true
markdown: redcarpet
timezone: Asia/Shanghai

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:

# ---------------------- #
# google analytics       #
# ---------------------- #
google_analytics: UA-11027907-1
